//
//  ProgressBarViewController.h
//  ProgressBar
//
//  Created by Aaron Schneider on 1/21/14.
//  Copyright (c) 2014 Pod 6. All rights reserved.
//
/*********************************
 The majority of this file is automatically generated by XCode when you create a new application.
 There are a couple of bits in didFinishLaunchWithOptions that initialize the view controller.
 *********************************/
#import <UIKit/UIKit.h>

@interface ProgressBarViewController : UIViewController
@property (nonatomic, retain) IBOutlet UIView* mProgressBarFillView;
@property (nonatomic, retain) IBOutlet UIView* mProgressBarFillBackgroundView;

@property (nonatomic, retain) IBOutletCollection(UIView) NSArray* mViewsToApplyCornerRadius;

- (IBAction)onStartPressed:(id)sender;
- (IBAction)onStopPressed:(id)sender;
- (IBAction)onResetPressed:(id)sender;
- (IBAction)onChunkDownPressed:(id)sender;
@end